name: Cache Nuget Packages
description: "Cache Nuget Packages compatible with Namespace Lab's runners"
inputs:
  namespacelabs:
    default: 'true'
    description: "Using Namespace Lab's runners"
branding:
  color: blue
  icon: archive
runs:
  using: 'composite'
  steps:
    # NAMESPACE LAB VERSION
    - uses: namespacelabs/nscloud-cache-action@v1
      with:
        path: ~/.nuget/packages
      if: inputs.namespacelabs == 'true'

    # NATIVE VERSION
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
      if: inputs.namespacelabs == 'false'
